name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install opy  # Install Opy for obfuscation
          pip install -r requirements.txt

      - name: Obfuscate code
        run: |
          opy index.py -o discordhacktool.py  # Obfuscate the main script

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole discordhacktool.py  # Build from the obfuscated script

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          release_name: latest
          files: dist/obfuscated_index.exe  # Adjust output file name if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
