name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pyarmor  # Install pyarmor for obfuscation
          pip install -r requirements.txt

      - name: Obfuscate code
        run: |
          pyarmor pack -x " --onefile --noconsole" index.py  # Obfuscate the code

      - name: Build executable
        run: |
          # Move the obfuscated executable to the dist folder
          mv dist/index.py obfuscated_index.py
          pyinstaller --onefile --noconsole obfuscated_index.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          release_name: latest
          files: dist/obfuscated_index.exe  # Update to the new executable name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
